/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VehicleService } from "../vehicle.service";
import { VehicleCreateInput } from "./VehicleCreateInput";
import { Vehicle } from "./Vehicle";
import { VehicleFindManyArgs } from "./VehicleFindManyArgs";
import { VehicleWhereUniqueInput } from "./VehicleWhereUniqueInput";
import { VehicleUpdateInput } from "./VehicleUpdateInput";
import { RecordFindManyArgs } from "../../record/base/RecordFindManyArgs";
import { Record } from "../../record/base/Record";
import { RecordWhereUniqueInput } from "../../record/base/RecordWhereUniqueInput";
import { VehicleSecretFindManyArgs } from "../../vehicleSecret/base/VehicleSecretFindManyArgs";
import { VehicleSecret } from "../../vehicleSecret/base/VehicleSecret";
import { VehicleSecretWhereUniqueInput } from "../../vehicleSecret/base/VehicleSecretWhereUniqueInput";

export class VehicleControllerBase {
  constructor(protected readonly service: VehicleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vehicle })
  async createVehicle(
    @common.Body() data: VehicleCreateInput
  ): Promise<Vehicle> {
    return await this.service.createVehicle({
      data: {
        ...data,

        dbc: data.dbc
          ? {
              connect: data.dbc,
            }
          : undefined,
      },
      select: {
        color: true,
        createdAt: true,

        dbc: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        make: true,
        model: true,
        name: true,
        secrets: true,
        trim: true,
        typeField: true,
        updatedAt: true,
        vin: true,
        year: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Vehicle] })
  @ApiNestedQuery(VehicleFindManyArgs)
  async vehicles(@common.Req() request: Request): Promise<Vehicle[]> {
    const args = plainToClass(VehicleFindManyArgs, request.query);
    return this.service.vehicles({
      ...args,
      select: {
        color: true,
        createdAt: true,

        dbc: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        make: true,
        model: true,
        name: true,
        secrets: true,
        trim: true,
        typeField: true,
        updatedAt: true,
        vin: true,
        year: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vehicle(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    const result = await this.service.vehicle({
      where: params,
      select: {
        color: true,
        createdAt: true,

        dbc: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        make: true,
        model: true,
        name: true,
        secrets: true,
        trim: true,
        typeField: true,
        updatedAt: true,
        vin: true,
        year: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVehicle(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() data: VehicleUpdateInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.updateVehicle({
        where: params,
        data: {
          ...data,

          dbc: data.dbc
            ? {
                connect: data.dbc,
              }
            : undefined,
        },
        select: {
          color: true,
          createdAt: true,

          dbc: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          make: true,
          model: true,
          name: true,
          secrets: true,
          trim: true,
          typeField: true,
          updatedAt: true,
          vin: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVehicle(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.deleteVehicle({
        where: params,
        select: {
          color: true,
          createdAt: true,

          dbc: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          make: true,
          model: true,
          name: true,
          secrets: true,
          trim: true,
          typeField: true,
          updatedAt: true,
          vin: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/records")
  @ApiNestedQuery(RecordFindManyArgs)
  async findRecords(
    @common.Req() request: Request,
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Record[]> {
    const query = plainToClass(RecordFindManyArgs, request.query);
    const results = await this.service.findRecords(params.id, {
      ...query,
      select: {
        begin: true,
        createdAt: true,

        data: {
          select: {
            id: true,
          },
        },

        end: true,
        id: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/records")
  async connectRecords(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        connect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/records")
  async updateRecords(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        set: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/records")
  async disconnectRecords(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        disconnect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/vehicleSecrets")
  @ApiNestedQuery(VehicleSecretFindManyArgs)
  async findVehicleSecrets(
    @common.Req() request: Request,
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<VehicleSecret[]> {
    const query = plainToClass(VehicleSecretFindManyArgs, request.query);
    const results = await this.service.findVehicleSecrets(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vehicleSecrets")
  async connectVehicleSecrets(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: VehicleSecretWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicleSecrets: {
        connect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vehicleSecrets")
  async updateVehicleSecrets(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: VehicleSecretWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicleSecrets: {
        set: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vehicleSecrets")
  async disconnectVehicleSecrets(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: VehicleSecretWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicleSecrets: {
        disconnect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
