/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Data } from "./Data";
import { DataCountArgs } from "./DataCountArgs";
import { DataFindManyArgs } from "./DataFindManyArgs";
import { DataFindUniqueArgs } from "./DataFindUniqueArgs";
import { CreateDataArgs } from "./CreateDataArgs";
import { UpdateDataArgs } from "./UpdateDataArgs";
import { DeleteDataArgs } from "./DeleteDataArgs";
import { RecordFindManyArgs } from "../../record/base/RecordFindManyArgs";
import { Record } from "../../record/base/Record";
import { DataService } from "../data.service";
@graphql.Resolver(() => Data)
export class DataResolverBase {
  constructor(protected readonly service: DataService) {}

  async _dataItemsMeta(
    @graphql.Args() args: DataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Data])
  async dataItems(@graphql.Args() args: DataFindManyArgs): Promise<Data[]> {
    return this.service.dataItems(args);
  }

  @graphql.Query(() => Data, { nullable: true })
  async data(@graphql.Args() args: DataFindUniqueArgs): Promise<Data | null> {
    const result = await this.service.data(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Data)
  async createData(@graphql.Args() args: CreateDataArgs): Promise<Data> {
    return await this.service.createData({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Data)
  async updateData(@graphql.Args() args: UpdateDataArgs): Promise<Data | null> {
    try {
      return await this.service.updateData({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Data)
  async deleteData(@graphql.Args() args: DeleteDataArgs): Promise<Data | null> {
    try {
      return await this.service.deleteData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Record], { name: "records" })
  async findRecords(
    @graphql.Parent() parent: Data,
    @graphql.Args() args: RecordFindManyArgs
  ): Promise<Record[]> {
    const results = await this.service.findRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
